language: c
language: java
language: python
env:
  global:
    - BUILD_BRANCH=$TRAVIS_BRANCH
    - BUILD_ID=$TRAVIS_BUILD_ID
matrix:
  include:
    - compiler: gcc
      os: linux
      env: BUILD_TARGET=linux
    - compiler: gcc
      os: linux
      env: BUILD_TARGET=win32
    - compiler: gcc
      os: linux
      env: BUILD_TARGET=win64
    - compiler: clang
      os: linux
      env: BUILD_TARGET=linux
    - compiler: gcc
      os: osx
      env: BUILD_TARGET=osx
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode7.3
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode7.2
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode7.1
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: beta-xcode6.1

before_deploy:
- export ARCHIVE=openaaa-$BUILD_TARGET.tar.gz
- ./scripts/archive.sh $ARCHIVE
- echo "deploying $(ARCHIVE) to GitHub Releases"

before_install:
- source ./scripts/version.sh $TRAVIS_BRANCH
- export VERSION="$BUILD_MAJOR"
- export PATCHLEVEL="$BUILD_MINOR"
- export SUBLEVEL="$BUILD_REVISION"

- if [[ "$BUILD_TARGET" == "win32" ]]; then 
    unset CC ; 
    export CROSS_COMPILE="i686-w64-mingw32-" ; 
    export MINGW=/opt/mingw64 ; 
    export PATH=$MINGW/bin:$PATH ; 
  fi 

- if [[ "$BUILD_TARGET" == "win64" ]]; then 
    unset CC ; 
    export CROSS_COMPILE="x86_64-w64-mingw32-"; 
    export MINGW=/opt/mingw64 ;
    export PATH=$MINGW/bin:$PATH ;
  fi

- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get -qq update ; 
    sudo apt-get install flex bison gperf libncurses-dev pkg-config ;
    sudo apt-get install binutils-mingw-w64-i686 gcc-mingw-w64-i686 ;
    sudo apt-get install binutils-mingw-w64 gcc-mingw-w64 ;
  fi

- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update ; 
    brew install flex bison gperftools ;
    unset CROSS_COMPILE ;
  fi

script:
- uname -a
- make defconfig
- make
