language: 
  - c
  - java
  - python
env:
  global:
    - BUILD_BRANCH=$TRAVIS_BRANCH
    - BUILD_ID=$TRAVIS_BUILD_ID
matrix:
  include:
    - compiler: gcc
      os: linux
      env: BUILD_TARGET=linux
    - compiler: gcc
      os: linux
      env: BUILD_TARGET=win32
    - compiler: gcc
      os: linux
      env: BUILD_TARGET=win64
    - compiler: clang
      os: linux
      env: BUILD_TARGET=linux
    - compiler: gcc
      os: osx
      env: BUILD_TARGET=osx
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode7.3
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode7.2
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode7.1
    - compiler: clang
      os: osx
      env: BUILD_TARGET=osx
      osx_image: beta-xcode6.1
before_deploy:
- export ARCHIVE=openaaa-$BUILD_TARGET.tar.gz
- ./scripts/archive.sh $ARCHIVE
- echo "deploying $(ARCHIVE) to GitHub Releases"
before_install:
- ./scripts/travis/before_install.sh
script:
- printenv
- uname -a
- make defconfig
- make
