/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opensec.aaa;

public final class aaa_protocol_e {
  public final static aaa_protocol_e PROTOCOL_MEMORY = new aaa_protocol_e("PROTOCOL_MEMORY", 1);
  public final static aaa_protocol_e PROTOCOL_UNIX = new aaa_protocol_e("PROTOCOL_UNIX", 2);
  public final static aaa_protocol_e PROTOCOL_UDP = new aaa_protocol_e("PROTOCOL_UDP", 3);
  public final static aaa_protocol_e PROTOCOL_TCP = new aaa_protocol_e("PROTOCOL_TCP", 4);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aaa_protocol_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aaa_protocol_e.class + " with value " + swigValue);
  }

  private aaa_protocol_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aaa_protocol_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aaa_protocol_e(String swigName, aaa_protocol_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aaa_protocol_e[] swigValues = { PROTOCOL_MEMORY, PROTOCOL_UNIX, PROTOCOL_UDP, PROTOCOL_TCP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

