/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opensec.aaa;

public final class aaa_object_type_e {
  public final static aaa_object_type_e STORAGE_TYPE_TEXT = new aaa_object_type_e("STORAGE_TYPE_TEXT", 1);
  public final static aaa_object_type_e STORAGE_TYPE_BINARY = new aaa_object_type_e("STORAGE_TYPE_BINARY", 2);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aaa_object_type_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aaa_object_type_e.class + " with value " + swigValue);
  }

  private aaa_object_type_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aaa_object_type_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aaa_object_type_e(String swigName, aaa_object_type_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aaa_object_type_e[] swigValues = { STORAGE_TYPE_TEXT, STORAGE_TYPE_BINARY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

