/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opensec.aaa;

public interface AttrConstants {
  public final static String ATTR_SESSION_ID = "sess.id";
  public final static String ATTR_SESSION_CHANNEL_ID = "sess.cid";
  public final static String ATTR_SESSION_CREATED = "sess.created";
  public final static String ATTR_SESSION_MODIFIED = "sess.modified";
  public final static String ATTR_SESSION_ACCESS = "sess.access";
  public final static String ATTR_SESSION_EXPIRES = "sess.expires";
  public final static String ATTR_SESSION_KEYING_MATERIAL = "sess.key";
  public final static String ATTR_SESSION_SECRET = "sess.sec";
  public final static String ATTR_USER_ID = "user.id";
  public final static String ATTR_USER_UUID = "user.uuid";
  public final static String ATTR_USER_NAME = "user.name";
  public final static String ATTR_USER_EMAIL = "user.email";
  public final static String ATTR_USER_GROUPS = "user.groups[]";
}
