/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opensec.aaa;

public class Attr implements AttrConstants {
  public static void aaa_init() {
    Link.aaa_init();
  }

  public static void aaa_fini() {
    Link.aaa_fini();
  }

  public static SWIGTYPE_p_aaa aaa_new() {
    long cPtr = Link.aaa_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p_aaa(cPtr, false);
  }

  public static void aaa_free(SWIGTYPE_p_aaa arg0) {
    Link.aaa_free(SWIGTYPE_p_aaa.getCPtr(arg0));
  }

  public static int aaa_bind(SWIGTYPE_p_aaa arg0, Bind type, String id) {
    return Link.aaa_bind(SWIGTYPE_p_aaa.getCPtr(arg0), type.swigValue(), id);
  }

  public static int aaa_attr_set(SWIGTYPE_p_aaa arg0, String attr, String value) {
    return Link.aaa_attr_set(SWIGTYPE_p_aaa.getCPtr(arg0), attr, value);
  }

  public static String aaa_attr_get(SWIGTYPE_p_aaa arg0, String attr) {
    return Link.aaa_attr_get(SWIGTYPE_p_aaa.getCPtr(arg0), attr);
  }

  public static int aaa_object_set(SWIGTYPE_p_aaa arg0, SWIGTYPE_p_void addr, long size) {
    return Link.aaa_object_set(SWIGTYPE_p_aaa.getCPtr(arg0), SWIGTYPE_p_void.getCPtr(addr), size);
  }

  public static SWIGTYPE_p_void aaa_object_get(SWIGTYPE_p_aaa arg0, SWIGTYPE_p_unsigned_int size) {
    long cPtr = Link.aaa_object_get(SWIGTYPE_p_aaa.getCPtr(arg0), SWIGTYPE_p_unsigned_int.getCPtr(size));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static int aaa_attr_del_value(SWIGTYPE_p_aaa arg0, String key, String val) {
    return Link.aaa_attr_del_value(SWIGTYPE_p_aaa.getCPtr(arg0), key, val);
  }

  public static int aaa_attr_has_value(SWIGTYPE_p_aaa arg0, String key, String val) {
    return Link.aaa_attr_has_value(SWIGTYPE_p_aaa.getCPtr(arg0), key, val);
  }

  public static String aaa_attr_find_first(SWIGTYPE_p_aaa arg0, String path, long recurse) {
    return Link.aaa_attr_find_first(SWIGTYPE_p_aaa.getCPtr(arg0), path, recurse);
  }

  public static String aaa_attr_find_next(SWIGTYPE_p_aaa arg0) {
    return Link.aaa_attr_find_next(SWIGTYPE_p_aaa.getCPtr(arg0));
  }

  public static int aaa_select(SWIGTYPE_p_aaa arg0, String path) {
    return Link.aaa_select(SWIGTYPE_p_aaa.getCPtr(arg0), path);
  }

  public static int aaa_touch(SWIGTYPE_p_aaa arg0) {
    return Link.aaa_touch(SWIGTYPE_p_aaa.getCPtr(arg0));
  }

  public static int aaa_commit(SWIGTYPE_p_aaa arg0) {
    return Link.aaa_commit(SWIGTYPE_p_aaa.getCPtr(arg0));
  }

  public static int aaa_set_opt(SWIGTYPE_p_aaa arg0, Option arg1, String arg2) {
    return Link.aaa_set_opt(SWIGTYPE_p_aaa.getCPtr(arg0), arg1.swigValue(), arg2);
  }

  public static String aaa_get_opt(SWIGTYPE_p_aaa arg0, Option arg1) {
    return Link.aaa_get_opt(SWIGTYPE_p_aaa.getCPtr(arg0), arg1.swigValue());
  }

  public static int aaa_last_error(SWIGTYPE_p_aaa arg0) {
    return Link.aaa_last_error(SWIGTYPE_p_aaa.getCPtr(arg0));
  }

}
