/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opensec.aaa;

public class Client {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Client(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Link.delete_Client(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Client() {
    this(Link.new_Client(), true);
  }

  public int bind(Bind k, String id) {
    return Link.Client_bind__SWIG_0(swigCPtr, this, k.swigValue(), id);
  }

  public int bind(Bind k) {
    return Link.Client_bind__SWIG_1(swigCPtr, this, k.swigValue());
  }

  public int setAttribute(String attr, String value) {
    return Link.Client_setAttribute(swigCPtr, this, attr, value);
  }

  public String getAttribute(String attr) {
    return Link.Client_getAttribute(swigCPtr, this, attr);
  }

  public int select(String path) {
    return Link.Client_select__SWIG_0(swigCPtr, this, path);
  }

  public int select() {
    return Link.Client_select__SWIG_1(swigCPtr, this);
  }

  public int commit() {
    return Link.Client_commit(swigCPtr, this);
  }

}
