/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.opensec.aaa;

public class Link {

static {
        try {
                System.loadLibrary("aaa");
        } catch (UnsatisfiedLinkError e) {
                System.err.println("Native code library failed to load. \n" + e);
                System.exit(1);
        }
}

  public final static native void aaa_init();
  public final static native void aaa_fini();
  public final static native long aaa_new();
  public final static native void aaa_free(long jarg1);
  public final static native int aaa_bind(long jarg1, int jarg2, String jarg3);
  public final static native int aaa_attr_set(long jarg1, String jarg2, String jarg3);
  public final static native String aaa_attr_get(long jarg1, String jarg2);
  public final static native int aaa_object_set(long jarg1, long jarg2, long jarg3);
  public final static native long aaa_object_get(long jarg1, long jarg2);
  public final static native int aaa_attr_del_value(long jarg1, String jarg2, String jarg3);
  public final static native int aaa_attr_has_value(long jarg1, String jarg2, String jarg3);
  public final static native String aaa_attr_find_first(long jarg1, String jarg2, long jarg3);
  public final static native String aaa_attr_find_next(long jarg1);
  public final static native int aaa_select(long jarg1, String jarg2);
  public final static native int aaa_touch(long jarg1);
  public final static native int aaa_commit(long jarg1);
  public final static native int aaa_set_opt(long jarg1, int jarg2, String jarg3);
  public final static native String aaa_get_opt(long jarg1, int jarg2);
  public final static native int aaa_last_error(long jarg1);
  public final static native long new_Client();
  public final static native void delete_Client(long jarg1);
  public final static native int Client_bind__SWIG_0(long jarg1, Client jarg1_, int jarg2, String jarg3);
  public final static native int Client_bind__SWIG_1(long jarg1, Client jarg1_, int jarg2);
  public final static native int Client_setAttribute(long jarg1, Client jarg1_, String jarg2, String jarg3);
  public final static native String Client_getAttribute(long jarg1, Client jarg1_, String jarg2);
  public final static native int Client_select__SWIG_0(long jarg1, Client jarg1_, String jarg2);
  public final static native int Client_select__SWIG_1(long jarg1, Client jarg1_);
  public final static native int Client_commit(long jarg1, Client jarg1_);
}
