DIRS+=utils

#marvin=$(o)/utils/marvin
#marvin_OBJECTS=$(addprefix $(o)/utils/, marvin)

#$(marvin): $(addsuffix .o, $(marvin_OBJECTS))
#$(marvin): $(LIBSYS_STATIC) $(LIBCOMPAT_STATIC) $(LIBMARVIN_STATIC) $(LIBS)

#PROGS+=$(marvin)
#ASM+=$(addsuffix .s, $(marvin_OBJECTS))

#marvind=$(o)/utils/marvind
#marvind_OBJECTS=$(addprefix $(o)/utils/, marvind)

#$(marvind): $(addsuffix .o, $(marvind_OBJECTS))
#$(marvind): $(LIBSYS_STATIC) $(LIBCOMPAT_STATIC) $(LIBMARVIN_STATIC) $(LIBS)

#PROGS+=$(marvind)
#ASM+=$(addsuffix .s, $(marvind_OBJECTS))
