/** @file uri-scheme-opt.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.5
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef URI_SCHEME_OPT_H
#define URI_SCHEME_OPT_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef SCHEME_PACKAGE
/** @brief the program name (used for printing errors) */
#define SCHEME_PACKAGE "uri-scheme"
#endif

#ifndef SCHEME_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define SCHEME_PACKAGE_NAME "uri-scheme"
#endif

#ifndef SCHEME_VERSION
/** @brief the program version */
#define SCHEME_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct scheme_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * name_arg;	/**< @brief uri::scheme name.  */
  char * name_orig;	/**< @brief uri::scheme name original value given at command line.  */
  const char *name_help; /**< @brief uri::scheme name help description.  */
  char * handler_arg;	/**< @brief uri::scheme handler .  */
  char * handler_orig;	/**< @brief uri::scheme handler  original value given at command line.  */
  const char *handler_help; /**< @brief uri::scheme handler  help description.  */
  char * about_arg;	/**< @brief uri::scheme about.  */
  char * about_orig;	/**< @brief uri::scheme about original value given at command line.  */
  const char *about_help; /**< @brief uri::scheme about help description.  */
  const char *list_help; /**< @brief uri::scheme list help description.  */
  const char *register_help; /**< @brief uri::scheme register help description.  */
  const char *unregister_help; /**< @brief uri::scheme unregister help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int name_given ;	/**< @brief Whether name was given.  */
  unsigned int handler_given ;	/**< @brief Whether handler was given.  */
  unsigned int about_given ;	/**< @brief Whether about was given.  */
  unsigned int list_given ;	/**< @brief Whether list was given.  */
  unsigned int register_given ;	/**< @brief Whether register was given.  */
  unsigned int unregister_given ;	/**< @brief Whether unregister was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct scheme_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure scheme_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure scheme_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *scheme_args_info_purpose;
/** @brief the usage string of the program */
extern const char *scheme_args_info_usage;
/** @brief all the lines making the help output */
extern const char *scheme_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int scheme (int argc, char **argv,
  struct scheme_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use scheme_ext() instead
 */
int scheme2 (int argc, char **argv,
  struct scheme_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int scheme_ext (int argc, char **argv,
  struct scheme_args_info *args_info,
  struct scheme_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int scheme_dump(FILE *outfile,
  struct scheme_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int scheme_file_save(const char *filename,
  struct scheme_args_info *args_info);

/**
 * Print the help
 */
void scheme_print_help(void);
/**
 * Print the version
 */
void scheme_print_version(void);

/**
 * Initializes all the fields a scheme_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void scheme_params_init(struct scheme_params *params);

/**
 * Allocates dynamically a scheme_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized scheme_params structure
 */
struct scheme_params *scheme_params_create(void);

/**
 * Initializes the passed scheme_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void scheme_init (struct scheme_args_info *args_info);
/**
 * Deallocates the string fields of the scheme_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void scheme_free (struct scheme_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int scheme_required (struct scheme_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* URI_SCHEME_OPT_H */
