DIRS+=src
include $(s)/src/arch/Makefile
include $(s)/src/net/Makefile
include $(s)/src/mem/Makefile
include $(s)/src/asm/Makefile
include $(s)/src/compat/Makefile
include $(s)/src/crypto/Makefile
include $(s)/src/getopt/Makefile
include $(s)/src/ctypes/Makefile
include $(s)/src/aaa/Makefile
include $(s)/src/aaa/net/Makefile
include $(s)/src/aaa/modules/Makefile

ifeq (${CONFIG_SWIG},1)
include $(s)/src/swig/Makefile
endif
